BEGIN TRANSACTION;

CREATE TABLE "Database" (
	"version"	INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE "Browser" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE "Entry" (
	"id" INTEGER NOT NULL,
	"timestamp"	INTEGER NOT NULL,
	"browserId"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("browserId") REFERENCES "Browser"("id") ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE "window" (
	"entryId"	INTEGER NOT NULL,
	"openTabs"	INTEGER NOT NULL,
	FOREIGN KEY("entryId") REFERENCES "Entry"("id") ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO `Database` (`version`) VALUES (0);

COMMIT;
