BEGIN TRANSACTION;

CREATE TABLE "Browser" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE "Database" (
	"version"	INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE "Entry" (
	"id"	INTEGER NOT NULL UNIQUE,
	"timestamp"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE "WindowInformation" (
	"entryId"	INTEGER NOT NULL,
	"browserId"	INTEGER NOT NULL,
	"tabs"	INTEGER NOT NULL,
	PRIMARY KEY("entryId","browserId"),
	FOREIGN KEY("browserId") REFERENCES "Browser"("id") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("entryId") REFERENCES "Entry"("id") ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO `Database` (`version`) VALUES (0);

COMMIT;
